import type { Metadata } from "next";
import "@/app/globals.css";
import { Navbar } from "@/components/example/navbar";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	// const cookieStore = await cookies();
	// const jwtToken = cookieStore.get("jwt");
	// let user_token;
	// if (jwtToken) {
	// 	user_token = jwtDecode<{ user_id: number | undefined }>(jwtToken?.value); // Define the expected structure
	// } else {
	// 	return null;
	// }

	return (
		<>
			<Navbar />
			{children}
		</>
	);
}
